### ISSUE TITLE
Not working (unintended global check)

### ISSUE THREAD

**Issue by Road-block** [gashole/DruidManaBar#1]
https://github.com/gashole/DruidManaBar/blob/15a8c355f68de17dd6e1b935fa531db790920f1f/DruidManaBar.lua#L1

https://github.com/gashole/DruidManaBar/blob/15a8c355f68de17dd6e1b935fa531db790920f1f/Localization.lua#L1

Both files reference an uninitialized global variable `playerClass` that has no value, so the addon never loads.

The variable **is** properly assigned to a local in DruidManaLib but that's never used.

**Comment by Road-block** [comment]
One simple fix is using
```lua
local _,playerClass = UnitClass("player")
```
above both those checks.

**Comment by AMGarkin** [comment]
FYI:
It works with included version of [DruidManaLib-1.0](https://github.com/gashole/DruidManaBar/blob/master/libs/DruidManaLib-1.0/DruidManaLib-1.0.lua#L123), as it makes variable playerClass global. But it doesn't work with the newest version of [DruidManaLib-1.0](https://github.com/Aviana/LunaUnitFrames/blob/master/libs/DruidManaLib-1.0/DruidManaLib-1.0.lua).

**Comment by gashole** [comment]
Fixed by https://github.com/gashole/DruidManaBar/commit/39cbb7d6ea8b6eb960bcaf72c26e96d2091f1230
